### ISSUE TITLE
some question about ganglia's result 

### ISSUE THREAD

**Issue by zongwan** [wookietreiber/dockerfiles#4]
The report of ganglia docker container => ?
1. status about docker-vm ?
2. status about server ?
3. status about docker-container ?

can I link this container with the container of my product for receiving better report ?

Glad to see a lastest commit in last week.

**Comment by wookietreiber** [comment]
It starts gmetad, gmond and httpd inside the container, see the start.sh script. See the systemd or sysvinit scripts for to start it to forward the port and store the rrds.
